export default {
  SKU:{
    name:'SKU',
    type:'input',
    roles:[
      {type:"string",min:1},
      {type:"string",max:40}
    ]
  },
  StandardProductID:{
    name:'StandardProductID',
    type:'label',
    child:{
      Type:{
        name:'Type',
        type:'select',
        values:['ISBN','UPC','EAN','ASIN','GTIN','GCID','PZN'],
        roles:[
          {type:"enum",enum:['ISBN','UPC','EAN','ASIN','GTIN','GCID','PZN']}
        ]
      },
      Value:{
        name:'Value',
        type:'input',
        roles:[
          {type:'string',min:8},
          {type:'string',max:16}
        ]
      }
    }
  },
  GtinExemptionReason:{
    name:'GtinExemptionReason',
    type:'select',
    values:['bundle','part'],
    roles:[
      {type:"enum",enum:['bundle','part']}
    ]
  },
  RelatedProductID:{
    name:'RelatedProductID',
    type:'lable',
    child:{
      Type:{
        name:'Type',
        type:'select',
        values:['UPC','EAN','GTIN'],
        roles:[
          {type:'enum',enum:['UPC','EAN','GTIN']}
        ]
      },
      Value:{
        name:'Value',
        type:'input',
        roles:[
          {type:'string',min:8},
          {type:'string',max:16}
        ]
      }
    }
  }
}