const Product = {
    "SKU":{
        rules:{
            min:1,
            max:40
        },
        type:'input'
    },
    "StandardProductID":{
        "Type":{
            rules:{
                in:['ISBN','UPC','EAN','ASIN','GTIN','GCID','PZN']
            },
            type:'select'
        },
        "Value":{
            rules:{
                min:8,
                max:16
            },
            type:'input'
        }
    },
    "GtinExemptionReason":{
        rules:{
            in:['bundle','part']
        },
        type:'select'
    },
    "RelatedProductID":{
        "Type":{
            rules:{
                in:['UPC','EAN','GTIN']
            },
            type:'select'
        },
        "Value":{
            rules:{
                min:8,
                max:16
            },
            type:'input'
        }
    },
    "ProductTaxCode":{
        rules:{
            min:1,
            max:50
        },
        type:'input'
    },
    "LaunchDate":{
        type:'input'
    },
    "DiscontinueDate":{
        type:'input'
    },
    "ReleaseDate":{
        type:'input'
    },
    "ExternalProductUrl":{
        rules:{
            url:true
        }
    },
    "ConditionInfo":{
        "ConditionType":{
            rules:{
                in:['New','UsedLikeNew','UsedVeryGood','UsedGood','UsedAcceptable','CollectibleLikeNew','CollectibleVeryGood','CollectibleGood','CollectibleAcceptable','Refurbished','Club']
            },
            type:'select'
        },
        "ConditionNote":{
            rules:{
                max:2000
            },
            type:'select'
        }
    },
    "Rebate":{
        // 最大出现次数2
        "RebateStartDate":{
            // dateTime
        },
        "RebateEndDate":{
            // dateTime
        },
        "RebateMessage":{
            rules:{
                min:1,
                max:250
            }
        },
        "RebateName":{
            rules:{
                min:1,
                max:40
            }
        },
        "ItemPackageQuantity":{
            rules:{
                numeric:true
            }
        }
    }
}

